### ISSUE TITLE
Session is not instantiable while building [DinhQuocHan\Twig\Extensions\Session

### ISSUE THREAD

**Issue by chesterlaykin** [dinhquochan/laravel-twig#2]
Hi!
I want to use Twig in Laravel Lumen, so I thought this package may be just what I need!

Is the package ready to use?

I run into this error:
`Target [Illuminate\Contracts\Session\Session] is not instantiable while building [DinhQuocHan\Twig\Extensions\Session]`

This is when I'm trying to access a test page
**route:**
```
$router->get('/twigtest', function () use ($router) { 
    return view('test');
});
```

**test.twig:**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Twig test</title>
</head>
<body>
        <h1>Twig test</h1>
</body>
</html>
```

**Comment by dinhquochan** [comment]
Now, I do not test on Lumen. I think I should add configurable on active extensions, can you disable Session Extension manual?

**Comment by dinhquochan** [comment]
I tested Lumen. Now, you can use. But Lumen does not support auto re-compiled views. You must use `php artisan view:clear` after edit file.

**Comment by chesterlaykin** [comment]
Okay, cool. I ran php artisan view:clear but get an error when trying to extend a view template ("View [master.twig] not found."). Maybe some Lumen incompatibility or maybe something I overlooked.
If I run the view for my "master.twig" template, I instead get error when it tries to include an header partial:
`{% include 'partials/_head.twig' %}`

"View [partials/_head.twig] not found."

**Edit**: My mistake, apparently I should write` {%  extends 'master' %}` , not` {%  extends 'master.twig' %} `. Maybe they changed that from v1 to v2. So it seems to work.

**Comment by Aleksey203** [comment]
You need to bind Session on Lumen:
`$app->singleton(
    Illuminate\Contracts\Session\Session::class,
    function ($app) {
        return (new SessionManager($app))->driver();
    }
);`
