### ISSUE TITLE
Support for Laravel 8.x

### ISSUE THREAD

**Issue by jvdyck** [dinhquochan/laravel-twig#5]
Hello, I get a requirements error when trying to add laravel-twig to my new Laravel 8.x project.

I think this could possibly be fixed by changing the requirements in `composer.json` from `^6|^7` to `^6|^7|^8`. Ofcourse Laravel 6.x and 7.x should keep working for projects depending on it. If you'd like, I can create a PR for the suggested fix.

**Comment by dinhquochan** [comment]
You're welcome.

**Comment by jvdyck** [comment]
The problem is that I don't understand the structure of this repo: your latest release is v1.2.0 (3 March 2020), but: `This commit does not belong to any branch on this repository.`
So while it's only a small change, I don't know how to commit it because `master` contains other changes, but lacks some changes from v1.2.0...

**Comment by jvdyck** [comment]
Thank you!
